name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/shared/set-up

      - name: Analyze code
        shell: bash
        run: flutter analyze

  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/shared/set-up

      - name: Run tests
        shell: bash
        run: flutter test --coverage

  format:
    name: Format
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/shared/set-up

      - name: Set up formatting tools
        shell: bash
        run: dart run scripts/setup.dart

      - name: Check formatting
        uses: dprint/check@v2.2
