name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: macos-latest

    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: Analyze code
        run: flutter analyze

  test:
    name: Test
    runs-on: macos-latest

    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: Run tests
        run: flutter test --coverage

  format:
    name: Format
    runs-on: macos-latest

    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: Check formatting
        run: flutter format --set-exit-if-changed .
