name: Shared set-up workflow

on:
  workflow_call:

jobs:
  set-up:
    name: Set-up tools and dependencies
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set-up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Disable analytics
        run: |
          dart --disable-analytics
          flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get
